apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cilium-cluster
servers: 1
agents: 2
ports:
  - port: 6443:6443 # Kubernetes API Server
    nodeFilters:
      - loadbalancer
  - port: 8080:80 # Expose services on localhost:8080
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
